imports:
    - { resource: parameters.dist.yml }
    - { resource: parameters.yml }

framework:
    secret: %secret%
    charset: UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    templating: { engines: [twig] }
    form: ~
    csrf_protection: ~
    session: { auto_start: true }
    translator: ~

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        path: %database_path%
        charset: UTF8
    orm:
        auto_mapping: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
