parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

    database_driver: pdo_mysql
    database_host: localhost
    database_port: ~
    database_name: launchpad
    database_user: root
    database_password: ~
    database_path: ~
