Rithis\LaunchpadBundle\Entity\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        role:
            type: string
            length: 32
